Simav/Controllers/KullaniciController.cs
using App.Common.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Simav.Common;
using Simav.Core;
using Simav.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Simav.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly IService<Kullanicilar> _service;
        public KullaniciController(IService<Kullanicilar> service)
        {
            _service = service;
        }
        [AutFilter]
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Baslik = "Kullanici Listesi";
            var kullaniciListesi = _service.GetAll();
            return View(kullaniciListesi);
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Kullanicilar entity)
        {
            var kullanici = _service.Find(x => x.KullaniciAdi.Equals(entity.KullaniciAdi) && x.Password.Equals(entity.Password));
            if (kullanici != null)
            {
                HttpContext.Session.SetString("OturumAcik", "true");
                SessionInfo.GirisTarihi = DateTime.Now;
                SessionInfo.GirisYapanKullaniciId = kullanici.KullaniciId;
                SessionInfo.KullaniciAdSoyad = kullanici.Ad + " " + kullanici.Soyad;
                return RedirectToAction("Index", "Haberler");
            }
            else
            {
                ModelState.AddModelError("", "Kullanici veya Şifre Hatalı!");
                return View();
            }
        }
    }
}

Simav/Controllers/VideolarController.cs
using App.Common.Filters;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Simav.Common;
using Simav.Core;
using Simav.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Simav.Controllers
{
    public class VideolarController : Controller
    {

        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IService<Videolar> _service;
        public VideolarController(IService<Videolar> service, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _service = service;
        }
        public IActionResult VideoListesi()
        {
            ViewBag.Baslik = "Video Listesi";
            var haberListesi = _service.FindAll(x => x.Durum.Equals((byte)Enums.KayitDurumu.Aktif));
            return View(haberListesi);
        }
        public IActionResult VideoDetayi(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _service.GetById(id.Value);
            if (entity == null)
            {
                return NotFound();//Bulunamadı
            }
            return View(entity);
        }
        [AutFilter]
        [HttpGet]
        public IActionResult Index()
        {
            var entity = _service.FindAll(x => x.Durum.Equals((byte)Enums.KayitDurumu.Aktif)); ;
            return View(entity);
        }
        [AutFilter]
        [HttpGet]
        public IActionResult YeniVideo()
        {
            ViewBag.Baslik = "Yeni Video";
            return View();
        }
        [AutFilter]
        [HttpPost]
        public async Task<IActionResult> YeniVideolarAsync(Videolar entity, IFormFile uploaded_File)
        {
            if (uploaded_File == null || uploaded_File.Length == 0)
            {
                ModelState.AddModelError("", "Resim Seçilmedi!");
                return View();
            }
            if (uploaded_File.ContentType.IndexOf("image", StringComparison.OrdinalIgnoreCase) < 0)

            {
                ModelState.AddModelError("", "Resim Seçilmedi!");
                return View();
            }
            string sImage_Folder = "Video_Image";
            string sTarget_Filename = "Video_Image_" + DateTime.Now.ToString().Replace(" ", string.Empty).Replace(":", string.Empty) + ".jpg";
            string sPath_WebRoot = _hostEnvironment.WebRootPath;
            string sPath_of_Target_Folder = sPath_WebRoot + "\\images\\" + sImage_Folder + "\\";
            string sFile_Target_Original = sPath_of_Target_Folder + sTarget_Filename;
            using (var stream = new FileStream(sFile_Target_Original, FileMode.Create))
            {
                await uploaded_File.CopyToAsync(stream);
            }
            entity.Resim = sTarget_Filename;
            entity.DegistirenKulId = SessionInfo.GirisYapanKullaniciId;
            entity.DegistirmeTarihi = DateTime.Now;
            entity.KaydedenKulId = SessionInfo.GirisYapanKullaniciId;
            entity.KayıtTarihi = DateTime.Now;
            entity.Durum = (byte)Enums.KayitDurumu.Aktif;
            _service.Save(entity);
            return RedirectToAction("Index", "Projeler");
        }
        [AutFilter]
        [HttpGet]
        public IActionResult VideolarGuncelle(int? id)
        {
            ViewBag.Baslik = "Video Düzenle";
            if (id == null)
            {
                return NotFound();
            }
            var entity = _service.GetById(id.Value);
            if (entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }
        [AutFilter]
        [HttpPost]
        public async Task<IActionResult> VideolarGuncelleAsync(Videolar entity, IFormFile uploaded_File)
        {

            ViewBag.Baslik = "Video Güncelle";
            if (ModelState.IsValid)
            {
                if (uploaded_File == null || uploaded_File.Length == 0)
                {
                    ModelState.AddModelError("", "Resim Seçilmedi!");
                    return View();
                }
                if (uploaded_File.ContentType.IndexOf("image", StringComparison.OrdinalIgnoreCase) < 0)

                {
                    ModelState.AddModelError("", "Resim Seçilmedi!");
                    return View();
                }
                string sImage_Folder = "Video_Image";
                string sTarget_Filename = "Video_Image_" + DateTime.Now.ToString().Replace(" ", string.Empty).Replace(":", string.Empty) + ".jpg";
                string sPath_WebRoot = _hostEnvironment.WebRootPath;
                string sPath_of_Target_Folder = sPath_WebRoot + "\\images\\" + sImage_Folder + "\\";
                string sFile_Target_Original = sPath_of_Target_Folder + sTarget_Filename;
                using (var stream = new FileStream(sFile_Target_Original, FileMode.Create))
                {
                    await uploaded_File.CopyToAsync(stream);
                }
                entity.Resim = sTarget_Filename;
                entity.DegistirenKulId = SessionInfo.GirisYapanKullaniciId;
                entity.DegistirmeTarihi = DateTime.Now;
                _service.Update(entity);
                return RedirectToAction("Index");
            }
            return View(entity);
        }
        [AutFilter]
        [HttpGet]
        public IActionResult VideolarDetaylar(int? id)
        {
            ViewBag.Baslik = "Video Detayları";
            if (id == null)
            {
                return NotFound();
            }
            var entity = _service.GetById(id.Value);
            if (entity == null)
            {
                return NotFound();//Bulunamadı
            }
            return View(entity);
        }
        public JsonResult VideolarSil(int pId)
        {
            try
            {
                var entity = _service.GetById(pId);
                if (entity == null)
                {
                    return Json(new { basarili = false, id = pId, mesaj = "İşlem Başarısız" });
                }
                entity.Durum = (byte)Enums.KayitDurumu.Silinmiş;
                _service.Update(entity);
            }
            catch (Exception)
            {
                return Json(new { basarili = false, id = pId, mesaj = "İşlem Başarısız" });
            }
            return Json(new { basarili = true, id = pId, mesaj = "İşlem Başarılı" });
        }
    }
}

Simav/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Title = "Kullanici Bilgileri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/sidebars.css" rel="stylesheet" />
<link href="~/css/AdminMenu.css" rel="stylesheet" />
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<div class="container">
<div class="row">
    <div class="col-sm-4 col-md-3 sidebar">
        <div class="mini-submenu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </div>
        <div class="list-group">
            <span href="#" class="list-group-item active">
                Yönetici Paneli
                <span class="pull-right" id="slide-submenu">
                    <i class="fa fa-times"></i>
                </span>
            </span>
            <a asp-controller="Haberler" asp-action="Index" class="list-group-item">
                <i class="fa fa-comment-o"></i> Haberler
            </a>
            <a asp-controller="Duyuru" asp-action="Index" class="list-group-item">
                <i class="fa fa-search"></i> Duyurular
            </a>
            <a asp-controller="Bilgilendirme" asp-action="Index" class="list-group-item">
                <i class="fa fa-user"></i> Bilgilendirme
            </a>
            <a asp-controller="Etkinlikler" asp-action="Index" class="list-group-item">
                <i class="fa fa-folder-open-o"></i> Etkinlikler 
            </a>
            <a asp-controller="Ilanlar" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Ilanlar 
            </a>
            <a asp-controller="Ihaleler" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> İhaleler 
            </a>
            <a asp-controller="Sayfalar" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Sayfalar 
            </a>
            <a asp-controller="MeclisGundem" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Meclis Gündem İşlemleri 
            </a>
            <a asp-controller="Olum" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Olumler 
            </a>
            <a asp-controller="Personel" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Personel 
            </a>
            <a asp-controller="Projeler" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Projeler 
            </a>
            <a asp-controller="Sikayetler" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Sikayetler 
            </a>
            <a asp-controller="Videolar" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Videolar 
            </a>
            <a asp-controller="Kullanici" asp-action="Index" class="list-group-item">
                <i class="fa fa-bar-chart-o"></i> Kullanci İşlemleri 
            </a>
        </div>
    </div>

    <div class="col-sm-8 col-md-8 ">
        @RenderBody()
    </div>
</div>

<script src="~/vendor/bootstrap/js/popper.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/js/sidebars.js"></script>
<script src="~/js/KullaniciJS.js"></script>